//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RagnaCustoms.Resources.app {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RagnaCustoms.Resources.app.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Difficulties.
        /// </summary>
        internal static string Difficulties {
            get {
                return ResourceManager.GetString("Difficulties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable auto close after download?.
        /// </summary>
        internal static string Enable_auto_close_after_download_ {
            get {
                return ResourceManager.GetString("Enable auto close after download?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable OneClick download?.
        /// </summary>
        internal static string Enable_OneClick_download_ {
            get {
                return ResourceManager.GetString("Enable OneClick download?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enabled ?.
        /// </summary>
        internal static string Enabled__ {
            get {
                return ResourceManager.GetString("Enabled ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oups! nothing found, the select list is empty. .
        /// </summary>
        internal static string Error_1 {
            get {
                return ResourceManager.GetString("Error 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You need to fill all input in this tab.
        /// </summary>
        internal static string Error_2 {
            get {
                return ResourceManager.GetString("Error 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Get your Twitch Chat OAuth Password on.
        /// </summary>
        internal static string Get_your_Twitch_Chat_OAuth_Password_on {
            get {
                return ResourceManager.GetString("Get your Twitch Chat OAuth Password on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à song not found.
        /// </summary>
        internal static string Map_not_found {
            get {
                return ResourceManager.GetString("Map not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mapped by.
        /// </summary>
        internal static string Mapped_by {
            get {
                return ResourceManager.GetString("Mapped by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ragnarock application found.
        /// </summary>
        internal static string Ragnarock_application_found {
            get {
                return ResourceManager.GetString("Ragnarock application found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ragnarock application not found please refresh.
        /// </summary>
        internal static string Ragnarock_application_not_found_please_refresh {
            get {
                return ResourceManager.GetString("Ragnarock application not found please refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Request informations.
        /// </summary>
        internal static string RequestInfo {
            get {
                return ResourceManager.GetString("RequestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Twitch bot.
        /// </summary>
        internal static string Twitch_bot {
            get {
                return ResourceManager.GetString("Twitch bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Twitch Chat OAuth password.
        /// </summary>
        internal static string Twitch_Chat_OAuth_password {
            get {
                return ResourceManager.GetString("Twitch Chat OAuth password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hi ! I&apos;m http://RagnaCustoms.com &apos;s bot, you can click on the purple button of a song and paste it here. &quot;!rc help&quot; for more informations.
        /// </summary>
        internal static string WelcomeBot {
            get {
                return ResourceManager.GetString("WelcomeBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your Twitch channel.
        /// </summary>
        internal static string Your_Twitch_channel {
            get {
                return ResourceManager.GetString("Your Twitch channel", resourceCulture);
            }
        }
    }
}
