//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RagnaCustoms.Resources.twitchBot {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RagnaCustoms.Resources.twitchBot.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à asked by.
        /// </summary>
        internal static string asked_by {
            get {
                return ResourceManager.GetString("asked by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bot connected !.
        /// </summary>
        internal static string bot_connected__ {
            get {
                return ResourceManager.GetString("bot connected !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Camera changed.
        /// </summary>
        internal static string Camera_changed {
            get {
                return ResourceManager.GetString("Camera changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Camera error.
        /// </summary>
        internal static string Camera_error {
            get {
                return ResourceManager.GetString("Camera error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End of the queue.
        /// </summary>
        internal static string End_of_the_queue {
            get {
                return ResourceManager.GetString("End of the queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error on command..
        /// </summary>
        internal static string Error_on_command_ {
            get {
                return ResourceManager.GetString("Error on command.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go to https://ragnacustoms.com, click on the twitch button to copy !rc &lt;songid&gt; and paste it here.
        /// </summary>
        internal static string Go_to_https___ragnacustoms_com__click_on_the_twitch_button_to_copy__rc__songid__and_paste_it_here {
            get {
                return ResourceManager.GetString("Go to https://ragnacustoms.com, click on the twitch button to copy !rc <songid> a" +
                        "nd paste it here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Help 1/2 : !rc cam &lt;numero cam [1-5]&gt; (switch camera), !rc dev (information about dev), !rc help (this command), !rc &lt;song id&gt; (download the map), !rc cancel (remove last song you request).
        /// </summary>
        internal static string Help_1_2____rc_cam__numero_cam__1_5____switch_camera____rc_dev__information_about_dev____rc_help__this_command____rc__song_id___download_the_map____rc_cancel__remove_last_song_you_request_ {
            get {
                return ResourceManager.GetString("Help 1/2 : !rc cam <numero cam [1-5]> (switch camera), !rc dev (information about" +
                        " dev), !rc help (this command), !rc <song id> (download the map), !rc cancel (re" +
                        "move last song you request)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Help 2/2 : !rc open (open queue), !rc close (close queue), !rc shift (remove first song in list), !rc queue (list of songs not played), !rc next (next song to play), !rc version (to know current version).
        /// </summary>
        internal static string Help_2_2____rc_open__open_queue____rc_close__close_queue____rc_shift__remove_first_song_in_list____rc_queue__list_of_songs_not_played____rc_next__next_song_to_play____rc_version__to_know_current_version_ {
            get {
                return ResourceManager.GetString("Help 2/2 : !rc open (open queue), !rc close (close queue), !rc shift (remove firs" +
                        "t song in list), !rc queue (list of songs not played), !rc next (next song to pl" +
                        "ay), !rc version (to know current version)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I&apos;m version.
        /// </summary>
        internal static string I_m_version {
            get {
                return ResourceManager.GetString("I\'m version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My dev is Rhokapa.
        /// </summary>
        internal static string My_dev_is_Rhokapa {
            get {
                return ResourceManager.GetString("My dev is Rhokapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Next song :.
        /// </summary>
        internal static string Next_song__ {
            get {
                return ResourceManager.GetString("Next song :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Next songs are :.
        /// </summary>
        internal static string Next_songs_are__ {
            get {
                return ResourceManager.GetString("Next songs are :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No More song to remove.
        /// </summary>
        internal static string No_More_song_to_remove {
            get {
                return ResourceManager.GetString("No More song to remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Queue is already closed.
        /// </summary>
        internal static string Queue_is_already_closed {
            get {
                return ResourceManager.GetString("Queue is already closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Queue is already open.
        /// </summary>
        internal static string Queue_is_already_open {
            get {
                return ResourceManager.GetString("Queue is already open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Queue is closed.
        /// </summary>
        internal static string Queue_is_closed {
            get {
                return ResourceManager.GetString("Queue is closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Queue is now closed.
        /// </summary>
        internal static string Queue_is_now_closed {
            get {
                return ResourceManager.GetString("Queue is now closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Queue is now open.
        /// </summary>
        internal static string Queue_is_now_open {
            get {
                return ResourceManager.GetString("Queue is now open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ready !.
        /// </summary>
        internal static string Ready__ {
            get {
                return ResourceManager.GetString("Ready !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Song Cancelled :.
        /// </summary>
        internal static string Song_Cancelled__ {
            get {
                return ResourceManager.GetString("Song Cancelled :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Song removed.
        /// </summary>
        internal static string Song_removed {
            get {
                return ResourceManager.GetString("Song removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sorry only moderator can do that..
        /// </summary>
        internal static string Sorry_only_moderator_can_do_that_ {
            get {
                return ResourceManager.GetString("Sorry only moderator can do that.", resourceCulture);
            }
        }
    }
}
