//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RagnaCustoms.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }


        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RagnaCustoms.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can request custom maps to {0} with the command !rc [map_id], to find it go to https://ragnacustoms.com and click on the twitch button (the purple one) to copy !rc [map_id] command and come back here to paste the command..
        /// </summary>
        internal static string Command_Base_Action_Message {
            get {
                return ResourceManager.GetString("Command.Base.Action.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display how to request map to streamer.
        /// </summary>
        internal static string Command_Base_Help {
            get {
                return ResourceManager.GetString("Command.Base.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Cancelled.
        /// </summary>
        internal static string Command_Cancel_Action_Canceled {
            get {
                return ResourceManager.GetString("Command.Cancel.Action.Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No More song to remove.
        /// </summary>
        internal static string Command_Cancel_Action_NoSongToCancel {
            get {
                return ResourceManager.GetString("Command.Cancel.Action.NoSongToCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove your last request.
        /// </summary>
        internal static string Command_Cancel_Help {
            get {
                return ResourceManager.GetString("Command.Cancel.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        internal static string Command_Help_Action_Cmd {
            get {
                return ResourceManager.GetString("Command.Help.Action.Cmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of commands.
        /// </summary>
        internal static string Command_Help_Action_CommandList {
            get {
                return ResourceManager.GetString("Command.Help.Action.CommandList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To display the description of a command use &quot;!rc help [name_of_the_command]&quot;.
        /// </summary>
        internal static string Command_Help_Action_OthersCommand {
            get {
                return ResourceManager.GetString("Command.Help.Action.OthersCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This commande doesn&apos;t exists, check the command name..
        /// </summary>
        internal static string Command_Help_Action_UnknowCommand {
            get {
                return ResourceManager.GetString("Command.Help.Action.UnknowCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display list of commands.
        /// </summary>
        internal static string Command_Help_Help {
            get {
                return ResourceManager.GetString("Command.Help.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be careful, the API key is missing.\r\nGo to Tools &gt; Score system &gt; Configure Api key... .
        /// </summary>
        internal static string Program_Api_Message1 {
            get {
                return ResourceManager.GetString("Program.Api.Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key is missing.
        /// </summary>
        internal static string Program_Api_Message1_Title {
            get {
                return ResourceManager.GetString("Program.Api.Message1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Api key:.
        /// </summary>
        internal static string Program_Api_Set_api_key {
            get {
                return ResourceManager.GetString("Program.Api.Set_api_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Song_Form_About {
            get {
                return ResourceManager.GetString("Song.Form.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Song_Form_Author {
            get {
                return ResourceManager.GetString("Song.Form.Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto close Download.
        /// </summary>
        internal static string Song_Form_AutoCloseDownload {
            get {
                return ResourceManager.GetString("Song.Form.AutoCloseDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check access.
        /// </summary>
        internal static string Song_Form_CheckAccess {
            get {
                return ResourceManager.GetString("Song.Form.CheckAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare songs versions.
        /// </summary>
        internal static string Song_Form_CompareSongversion {
            get {
                return ResourceManager.GetString("Song.Form.CompareSongversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device found: {0} {1}.
        /// </summary>
        internal static string Song_Form_CompatibleDeviceFound {
            get {
                return ResourceManager.GetString("Song.Form.CompatibleDeviceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure API key....
        /// </summary>
        internal static string Song_Form_ConfigureApiKey {
            get {
                return ResourceManager.GetString("Song.Form.ConfigureApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulties.
        /// </summary>
        internal static string Song_Form_Difficulties {
            get {
                return ResourceManager.GetString("Song.Form.Difficulties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable overlay.
        /// </summary>
        internal static string Song_Form_EnableOverlay {
            get {
                return ResourceManager.GetString("Song.Form.EnableOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your API key:.
        /// </summary>
        internal static string Song_Form_EnterYourApiKey {
            get {
                return ResourceManager.GetString("Song.Form.EnterYourApiKey", resourceCulture);
            }
        }
  
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Song_Form_Exit {
            get {
                return ResourceManager.GetString("Song.Form.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Song_Form_File {
            get {
                return ResourceManager.GetString("Song.Form.File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} found.
        /// </summary>
        internal static string Song_Form_found {
            get {
                return ResourceManager.GetString("Song.Form.found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get overlay URL.
        /// </summary>
        internal static string Song_Form_getOverlayurl {
            get {
                return ResourceManager.GetString("Song.Form.getOverlayurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Song_Form_Help {
            get {
                return ResourceManager.GetString("Song.Form.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Song_Form_Language {
            get {
                return ResourceManager.GetString("Song.Form.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file.
        /// </summary>
        internal static string Song_Form_LogFile {
            get {
                return ResourceManager.GetString("Song.Form.LogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Screen.
        /// </summary>
        internal static string Song_Form_LogScreen {
            get {
                return ResourceManager.GetString("Song.Form.LogScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapper.
        /// </summary>
        internal static string Song_Form_Mapper {
            get {
                return ResourceManager.GetString("Song.Form.Mapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Song_Form_Name {
            get {
                return ResourceManager.GetString("Song.Form.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to set your API key first.
        /// </summary>
        internal static string Song_Form_NeedToSetYourApiKeyFirst {
            get {
                return ResourceManager.GetString("Song.Form.NeedToSetYourApiKeyFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No compatible device found.
        /// </summary>
        internal static string Song_Form_NoCompatibleDeviceFound {
            get {
                return ResourceManager.GetString("Song.Form.NoCompatibleDeviceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest.
        /// </summary>
        internal static string Song_Form_Quest {
            get {
                return ResourceManager.GetString("Song.Form.Quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score system.
        /// </summary>
        internal static string Song_Form_ScoreSystem {
            get {
                return ResourceManager.GetString("Song.Form.ScoreSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Song_Form_Search {
            get {
                return ResourceManager.GetString("Song.Form.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send score automatically.
        /// </summary>
        internal static string Song_Form_SendScoreAutomatically {
            get {
                return ResourceManager.GetString("Song.Form.SendScoreAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Song_Form_Settings {
            get {
                return ResourceManager.GetString("Song.Form.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming.
        /// </summary>
        internal static string Song_Form_Streaming {
            get {
                return ResourceManager.GetString("Song.Form.Streaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync complete.
        /// </summary>
        internal static string Song_Form_SyncComplete {
            get {
                return ResourceManager.GetString("Song.Form.SyncComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync songs.
        /// </summary>
        internal static string Song_Form_SyncSong {
            get {
                return ResourceManager.GetString("Song.Form.SyncSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Song_Form_Tools {
            get {
                return ResourceManager.GetString("Song.Form.Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch bot.
        /// </summary>
        internal static string Song_Form_TwitchBot {
            get {
                return ResourceManager.GetString("Song.Form.TwitchBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string TwitchBot_Form_Author {
            get {
                return ResourceManager.GetString("TwitchBot.Form.Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-start?.
        /// </summary>
        internal static string TwitchBot_Form_AutoStart {
            get {
                return ResourceManager.GetString("TwitchBot.Form.AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot message prefix.
        /// </summary>
        internal static string TwitchBot_Form_BotMessagePrefix {
            get {
                return ResourceManager.GetString("TwitchBot.Form.BotMessagePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        internal static string TwitchBot_Form_Commands {
            get {
                return ResourceManager.GetString("TwitchBot.Form.Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string TwitchBot_Form_Configuration {
            get {
                return ResourceManager.GetString("TwitchBot.Form.Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled?.
        /// </summary>
        internal static string TwitchBot_Form_Enabled {
            get {
                return ResourceManager.GetString("TwitchBot.Form.Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Token At:.
        /// </summary>
        internal static string TwitchBot_Form_GetToken {
            get {
                return ResourceManager.GetString("TwitchBot.Form.GetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage custom commands.
        /// </summary>
        internal static string TwitchBot_Form_ManagebaseCommands {
            get {
                return ResourceManager.GetString("TwitchBot.Form.ManagebaseCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage base commands.
        /// </summary>
        internal static string TwitchBot_Form_ManageCustomCommands {
            get {
                return ResourceManager.GetString("TwitchBot.Form.ManageCustomCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song.
        /// </summary>
        internal static string TwitchBot_Form_Song {
            get {
                return ResourceManager.GetString("TwitchBot.Form.Song", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch bot requests.
        /// </summary>
        internal static string TwitchBot_Form_Title {
            get {
                return ResourceManager.GetString("TwitchBot.Form.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMI OAuth.
        /// </summary>
        internal static string TwitchBot_Form_TMI {
            get {
                return ResourceManager.GetString("TwitchBot.Form.TMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch Channel name.
        /// </summary>
        internal static string TwitchBot_Form_TwitchChannel {
            get {
                return ResourceManager.GetString("TwitchBot.Form.TwitchChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewer.
        /// </summary>
        internal static string TwitchBot_Form_Viewer {
            get {
                return ResourceManager.GetString("TwitchBot.Form.Viewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without https://twitch.tv.
        /// </summary>
        internal static string TwitchBot_Form_withoutHttp {
            get {
                return ResourceManager.GetString("TwitchBot.Form.withoutHttp", resourceCulture);
            }
        }
    }
}
