//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RagnaCustoms.App.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RagnaCustoms.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can request custom maps to {0} with the command !rc [map_id], to find it go to https://ragnacustoms.com and click on the twitch button (the purple one) to copy !rc [map_id] command and come back here to paste the command..
        /// </summary>
        internal static string Command_Base_Action_Message {
            get {
                return ResourceManager.GetString("Command.Base.Action.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display how to request map to streamer.
        /// </summary>
        internal static string Command_Base_Help {
            get {
                return ResourceManager.GetString("Command.Base.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Song Cancelled :.
        /// </summary>
        internal static string Command_Cancel_Action_Canceled {
            get {
                return ResourceManager.GetString("Command.Cancel.Action.Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No More song to remove.
        /// </summary>
        internal static string Command_Cancel_Action_NoSongToCancel {
            get {
                return ResourceManager.GetString("Command.Cancel.Action.NoSongToCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove your last request.
        /// </summary>
        internal static string Command_Cancel_Help {
            get {
                return ResourceManager.GetString("Command.Cancel.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Command.
        /// </summary>
        internal static string Command_Help_Action_Cmd {
            get {
                return ResourceManager.GetString("Command.Help.Action.Cmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of commands.
        /// </summary>
        internal static string Command_Help_Action_CommandList {
            get {
                return ResourceManager.GetString("Command.Help.Action.CommandList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To display the description of a command use &quot;!rc help [name_of_the_command]&quot;.
        /// </summary>
        internal static string Command_Help_Action_OthersCommand {
            get {
                return ResourceManager.GetString("Command.Help.Action.OthersCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This commande doesn&apos;t exists, check the command name..
        /// </summary>
        internal static string Command_Help_Action_UnknowCommand {
            get {
                return ResourceManager.GetString("Command.Help.Action.UnknowCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display list of commands.
        /// </summary>
        internal static string Command_Help_Help {
            get {
                return ResourceManager.GetString("Command.Help.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Be careful, the API key is missing.\r\nGo to Tools &gt; Score system &gt; Configure Api key... .
        /// </summary>
        internal static string Program_Api_Message1 {
            get {
                return ResourceManager.GetString("Program.Api.Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à API key is missing.
        /// </summary>
        internal static string Program_Api_Message1_Title {
            get {
                return ResourceManager.GetString("Program.Api.Message1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter your Api key:.
        /// </summary>
        internal static string Program_Api_Set_api_key {
            get {
                return ResourceManager.GetString("Program.Api.Set_api_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        internal static string Song_Form_About {
            get {
                return ResourceManager.GetString("Song.Form.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Author.
        /// </summary>
        internal static string Song_Form_Author {
            get {
                return ResourceManager.GetString("Song.Form.Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auto close Download.
        /// </summary>
        internal static string Song_Form_AutoCloseDownload {
            get {
                return ResourceManager.GetString("Song.Form.AutoCloseDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check access.
        /// </summary>
        internal static string Song_Form_CheckAccess {
            get {
                return ResourceManager.GetString("Song.Form.CheckAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compare songs versions.
        /// </summary>
        internal static string Song_Form_CompareSongversion {
            get {
                return ResourceManager.GetString("Song.Form.CompareSongversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configure API key....
        /// </summary>
        internal static string Song_Form_ConfigureApiKey {
            get {
                return ResourceManager.GetString("Song.Form.ConfigureApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Difficulties.
        /// </summary>
        internal static string Song_Form_Difficulties {
            get {
                return ResourceManager.GetString("Song.Form.Difficulties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable overlay.
        /// </summary>
        internal static string Song_Form_EnableOverlay {
            get {
                return ResourceManager.GetString("Song.Form.EnableOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter your API key:.
        /// </summary>
        internal static string Song_Form_EnterYourApiKey {
            get {
                return ResourceManager.GetString("Song.Form.EnterYourApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit.
        /// </summary>
        internal static string Song_Form_Exit {
            get {
                return ResourceManager.GetString("Song.Form.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File.
        /// </summary>
        internal static string Song_Form_File {
            get {
                return ResourceManager.GetString("Song.Form.File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} {1} found.
        /// </summary>
        internal static string Song_Form_found {
            get {
                return ResourceManager.GetString("Song.Form.found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Get overlay URL.
        /// </summary>
        internal static string Song_Form_getOverlayurl {
            get {
                return ResourceManager.GetString("Song.Form.getOverlayurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Help.
        /// </summary>
        internal static string Song_Form_Help {
            get {
                return ResourceManager.GetString("Song.Form.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        internal static string Song_Form_Language {
            get {
                return ResourceManager.GetString("Song.Form.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log file.
        /// </summary>
        internal static string Song_Form_LogFile {
            get {
                return ResourceManager.GetString("Song.Form.LogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log Screen.
        /// </summary>
        internal static string Song_Form_LogScreen {
            get {
                return ResourceManager.GetString("Song.Form.LogScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mapper.
        /// </summary>
        internal static string Song_Form_Mapper {
            get {
                return ResourceManager.GetString("Song.Form.Mapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        internal static string Song_Form_Name {
            get {
                return ResourceManager.GetString("Song.Form.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You need to set your API key first.
        /// </summary>
        internal static string Song_Form_NeedToSetYourApiKeyFirst {
            get {
                return ResourceManager.GetString("Song.Form.NeedToSetYourApiKeyFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No compatible device found.
        /// </summary>
        internal static string Song_Form_NoCompatibleDeviceFound {
            get {
                return ResourceManager.GetString("Song.Form.NoCompatibleDeviceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quest.
        /// </summary>
        internal static string Song_Form_Quest {
            get {
                return ResourceManager.GetString("Song.Form.Quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Score system.
        /// </summary>
        internal static string Song_Form_ScoreSystem {
            get {
                return ResourceManager.GetString("Song.Form.ScoreSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search.
        /// </summary>
        internal static string Song_Form_Search {
            get {
                return ResourceManager.GetString("Song.Form.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send score automatically.
        /// </summary>
        internal static string Song_Form_SendScoreAutomatically {
            get {
                return ResourceManager.GetString("Song.Form.SendScoreAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string Song_Form_Settings {
            get {
                return ResourceManager.GetString("Song.Form.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Streaming.
        /// </summary>
        internal static string Song_Form_Streaming {
            get {
                return ResourceManager.GetString("Song.Form.Streaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sync complete.
        /// </summary>
        internal static string Song_Form_SyncComplete {
            get {
                return ResourceManager.GetString("Song.Form.SyncComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sync songs.
        /// </summary>
        internal static string Song_Form_SyncSong {
            get {
                return ResourceManager.GetString("Song.Form.SyncSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tools.
        /// </summary>
        internal static string Song_Form_Tools {
            get {
                return ResourceManager.GetString("Song.Form.Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Twitch bot.
        /// </summary>
        internal static string Song_Form_TwitchBot {
            get {
                return ResourceManager.GetString("Song.Form.TwitchBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Author.
        /// </summary>
        internal static string TwitchBot_Form_Author {
            get {
                return ResourceManager.GetString("TwitchBot.Form.Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auto-start?.
        /// </summary>
        internal static string TwitchBot_Form_AutoStart {
            get {
                return ResourceManager.GetString("TwitchBot.Form.AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bot message prefix.
        /// </summary>
        internal static string TwitchBot_Form_BotMessagePrefix {
            get {
                return ResourceManager.GetString("TwitchBot.Form.BotMessagePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commands.
        /// </summary>
        internal static string TwitchBot_Form_Commands {
            get {
                return ResourceManager.GetString("TwitchBot.Form.Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration.
        /// </summary>
        internal static string TwitchBot_Form_Configuration {
            get {
                return ResourceManager.GetString("TwitchBot.Form.Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enabled?.
        /// </summary>
        internal static string TwitchBot_Form_Enabled {
            get {
                return ResourceManager.GetString("TwitchBot.Form.Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Get Token At:.
        /// </summary>
        internal static string TwitchBot_Form_GetToken {
            get {
                return ResourceManager.GetString("TwitchBot.Form.GetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage custom commands.
        /// </summary>
        internal static string TwitchBot_Form_ManagebaseCommands {
            get {
                return ResourceManager.GetString("TwitchBot.Form.ManagebaseCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage base commands.
        /// </summary>
        internal static string TwitchBot_Form_ManageCustomCommands {
            get {
                return ResourceManager.GetString("TwitchBot.Form.ManageCustomCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Song.
        /// </summary>
        internal static string TwitchBot_Form_Song {
            get {
                return ResourceManager.GetString("TwitchBot.Form.Song", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Twitch bot requests.
        /// </summary>
        internal static string TwitchBot_Form_Title {
            get {
                return ResourceManager.GetString("TwitchBot.Form.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TMI OAuth.
        /// </summary>
        internal static string TwitchBot_Form_TMI {
            get {
                return ResourceManager.GetString("TwitchBot.Form.TMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Twitch Channel name.
        /// </summary>
        internal static string TwitchBot_Form_TwitchChannel {
            get {
                return ResourceManager.GetString("TwitchBot.Form.TwitchChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Viewer.
        /// </summary>
        internal static string TwitchBot_Form_Viewer {
            get {
                return ResourceManager.GetString("TwitchBot.Form.Viewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Without https://twitch.tv.
        /// </summary>
        internal static string TwitchBot_Form_withoutHttp {
            get {
                return ResourceManager.GetString("TwitchBot.Form.withoutHttp", resourceCulture);
            }
        }
    }
}
